workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - publish:
          requires:
            - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install goss
          command: |
            mkdir ~/bin
            export GOSS_DST=~/bin
            export GOSS_FILES_STRATEGY=cp
            curl -fsSL https://goss.rocks/install | sh
            goss -version
      - run:
          name: Test
          command: |
            export PATH=$PATH:~/bin
            # Important, change from mount to work on remote docker, see https://github.com/aelsabbahy/goss/pull/271
            # If using machine image you do not need this.
            export GOSS_FILES_STRATEGY=cp
            test/runTests.sh junit
      - store_test_results:
          path: goss


  publish:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run:
          name: Docker Builds
          command: |
            echo "Building quued version of all images in images.txt"
